#!/bin/bash

# FlouriteBot Installer Script
# This script installs and configures FlouriteBot on your VPS

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════╗"
echo "║       FlouriteBot Installer v1.0          ║"
echo "║     Telegram Bot Installation Script      ║"
echo "╚═══════════════════════════════════════════╝"
echo -e "${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}Please run this script as root (use sudo)${NC}"
  exit 1
fi

# Function to check if command exists
command_exists() {
  command -v "$1" >/dev/null 2>&1
}

# Step 1: Install Node.js 18+
echo -e "\n${YELLOW}[1/8] Checking Node.js installation...${NC}"
if command_exists node; then
  NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
  if [ "$NODE_VERSION" -ge 18 ]; then
    echo -e "${GREEN}Node.js v$(node -v) is already installed${NC}"
  else
    echo -e "${YELLOW}Node.js version is too old. Installing Node.js 18...${NC}"
    curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
    apt-get install -y nodejs
  fi
else
  echo -e "${YELLOW}Installing Node.js 18...${NC}"
  curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
  apt-get install -y nodejs
fi
echo -e "${GREEN}Node.js $(node -v) installed${NC}"

# Step 2: Install PM2 globally
echo -e "\n${YELLOW}[2/8] Installing PM2...${NC}"
if command_exists pm2; then
  echo -e "${GREEN}PM2 is already installed${NC}"
else
  npm install -g pm2
  echo -e "${GREEN}PM2 installed successfully${NC}"
fi

# Step 3: Create the installation directory
echo -e "\n${YELLOW}[3/8] Creating installation directory...${NC}"
INSTALL_DIR="/var/www/flouritebot"
if [ -d "$INSTALL_DIR" ]; then
  echo -e "${YELLOW}Directory $INSTALL_DIR already exists. Backing up...${NC}"
  BACKUP_DIR="/var/www/flouritebot_backup_$(date +%Y%m%d_%H%M%S)"
  mv "$INSTALL_DIR" "$BACKUP_DIR"
  echo -e "${GREEN}Backup created at $BACKUP_DIR${NC}"
fi
mkdir -p "$INSTALL_DIR"
echo -e "${GREEN}Created $INSTALL_DIR${NC}"

# Step 4: Extract the ZIP file
echo -e "\n${YELLOW}[4/8] Extracting FlouriteBot files...${NC}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ZIP_FILE="$SCRIPT_DIR/FlouriteBot-Panel.zip"

if [ ! -f "$ZIP_FILE" ]; then
  echo -e "${RED}Error: FlouriteBot-Panel.zip not found in $SCRIPT_DIR${NC}"
  echo -e "${YELLOW}Please ensure FlouriteBot-Panel.zip is in the same directory as this script${NC}"
  exit 1
fi

# Install unzip if not available
if ! command_exists unzip; then
  apt-get install -y unzip
fi

unzip -o "$ZIP_FILE" -d "$INSTALL_DIR"
echo -e "${GREEN}Files extracted successfully${NC}"

# Step 5: Install npm dependencies
echo -e "\n${YELLOW}[5/8] Installing npm dependencies...${NC}"
cd "$INSTALL_DIR"
npm install --production
echo -e "${GREEN}Dependencies installed${NC}"

# Create logs directory
mkdir -p "$INSTALL_DIR/logs"

# Step 6: Configure the bot
echo -e "\n${YELLOW}[6/8] Configuring the bot...${NC}"
echo ""
echo -e "${BLUE}Please provide the following information:${NC}"
echo ""

# Ask for BOT_TOKEN
while true; do
  read -p "Enter your Telegram BOT_TOKEN: " BOT_TOKEN
  if [ -n "$BOT_TOKEN" ]; then
    break
  else
    echo -e "${RED}BOT_TOKEN cannot be empty. Please try again.${NC}"
  fi
done

# Ask for ADMIN_ID
while true; do
  read -p "Enter your Telegram ADMIN_ID: " ADMIN_ID
  if [ -n "$ADMIN_ID" ]; then
    break
  else
    echo -e "${RED}ADMIN_ID cannot be empty. Please try again.${NC}"
  fi
done

# Generate .env file
echo -e "\n${YELLOW}Generating .env file...${NC}"
cat > "$INSTALL_DIR/.env" << EOF
# FlouriteBot Configuration
# Generated by installer on $(date)

# Telegram Bot Token
BOT_TOKEN=$BOT_TOKEN

# Admin Telegram ID
ADMIN_ID=$ADMIN_ID

# Node Environment
NODE_ENV=production
EOF

chmod 600 "$INSTALL_DIR/.env"
echo -e "${GREEN}.env file created successfully${NC}"

# Step 7: Start the bot with PM2
echo -e "\n${YELLOW}[7/8] Starting FlouriteBot with PM2...${NC}"

# Stop existing instance if running
pm2 delete flouritebot 2>/dev/null || true

# Start the bot
cd "$INSTALL_DIR"
pm2 start ecosystem.config.js

# Save PM2 configuration
pm2 save

# Setup PM2 startup script
echo -e "\n${YELLOW}Setting up PM2 startup script...${NC}"
pm2 startup systemd -u root --hp /root
pm2 save

echo -e "${GREEN}Bot started successfully${NC}"

# Step 8: Display status
echo -e "\n${YELLOW}[8/8] Bot Status:${NC}"
echo ""
pm2 status

echo -e "\n${GREEN}"
echo "╔═══════════════════════════════════════════════════════════╗"
echo "║          FlouriteBot Installation Complete!               ║"
echo "╠═══════════════════════════════════════════════════════════╣"
echo "║  Installation Directory: /var/www/flouritebot             ║"
echo "║                                                           ║"
echo "║  Useful Commands:                                         ║"
echo "║    pm2 status          - Check bot status                 ║"
echo "║    pm2 logs flouritebot - View bot logs                   ║"
echo "║    pm2 restart flouritebot - Restart the bot              ║"
echo "║    pm2 stop flouritebot    - Stop the bot                 ║"
echo "║                                                           ║"
echo "║  Your bot is now running! Send /start to your bot.        ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo -e "${NC}"
